name: Build and Run Hello
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Make bin directory
      run: mkdir -p bin

    - name: Set Hello.bat Path
      run: |
        echo "echo Hello" > bin/hello.bat
        echo ";$(pwd)\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Run Hello.bat
      run: hello.bat
