name: Add Hello.bat to PATH

on: [push]

jobs:
  add_hello_to_path:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create bin directory
        run: mkdir -p bin

      - name: Create Hello.bat
        run: echo "echo Hello" > bin/hello.bat

      - name: Set bin directory to PATH
        run: echo "export PATH=$env:PATH;${{ github.workspace }}/bin" >> $GITHUB_ENV

      - name: Run Hello.bat
        run: hello.bat
