name: Set up Hello

on: [push]

jobs:
  setup:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Make bin directory
        run: mkdir -p bin

      - name: Create hello.bat
        run: echo "echo Hello" > bin/hello.bat

      - name: Add bin to PATH
        run: |
          echo "##[add-to-path]"$(pwd)/bin
          echo "PATH = $env:PATH"
          echo "BIN = "$(pwd)/bin
          echo "##[add-to-path]$(pwd)/bin"

      - name: Run Hello.bat
        run: hello
        shell: cmd
