name: Add Hello

on:
  push:
    branches:
      - main

jobs:
  add_hello:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Create Bin Folder
      run: mkdir -p bin
      
    - name: Add Hello to Bin Folder
      run: echo "echo Hello" > bin/hello.bat
      
    - name: Add Bin Folder to PATH
      run: |
        echo "export PATH=`pwd`/bin:\$PATH" >> $GITHUB_ENV
        echo $PATH
      
    - name: Run Hello
      run: hello.bat
      shell: cmd
