name: Hello Workflow
on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Make bin directory
        run: mkdir -p bin

      - name: Create hello.bat
        run: echo "echo Hello" > bin/hello.bat

      - name: Add bin to PATH
        run: echo "export PATH=$PATH:`pwd`/bin" >> $GITHUB_ENV

      - name: Display PATH
        run: echo $PATH

      - name: Run Hello
        run: hello.bat
        shell: cmd
